import {
  Coffee,
  Factory,
  Timer,
  Recycle,
  Wind,
  Waves,
  Trash2,
  Leaf,
  TrendingDown,
  DollarSign,
  Globe,
  Users,
  BarChart3,
  Ban,
  Zap,
  Award,
  History,
  Tag,
  Minimize2,
  Fish,
  Layers,
  Shield,
  UtensilsCrossed,
  Clock,
  Scale,
  Droplets,
  Cog,
  Flame,
  Atom,
  Sparkles,
  MapPin,
  HelpCircle,
  type LucideProps,
} from "lucide-react";
import React from "react";

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  coffee: Coffee,
  factory: Factory,
  timer: Timer,
  recycle: Recycle,
  wind: Wind,
  waves: Waves,
  trash2: Trash2,
  trash: Trash2,
  leaf: Leaf,
  "trending-down": TrendingDown,
  trendingdown: TrendingDown,
  "dollar-sign": DollarSign,
  dollarsign: DollarSign,
  globe: Globe,
  users: Users,
  "bar-chart-3": BarChart3,
  barchart3: BarChart3,
  barchart: BarChart3,
  ban: Ban,
  zap: Zap,
  award: Award,
  history: History,
  tag: Tag,
  minimize2: Minimize2,
  "minimize-2": Minimize2,
  fish: Fish,
  layers: Layers,
  shield: Shield,
  "utensils-crossed": UtensilsCrossed,
  utensilscrossed: UtensilsCrossed,
  utensils: UtensilsCrossed,
  clock: Clock,
  scale: Scale,
  droplets: Droplets,
  cog: Cog,
  flame: Flame,
  atom: Atom,
  sparkles: Sparkles,
  "map-pin": MapPin,
  mappin: MapPin,
  "help-circle": HelpCircle,
};

export function getIcon(iconName: string, className?: string): React.ReactNode {
  const normalizedName = iconName.toLowerCase().trim();
  const IconComponent = iconMap[normalizedName] || HelpCircle;
  return <IconComponent className={className || "w-5 h-5"} />;
}

export default getIcon;
